float:
  any:
  # --- CP-HNSW Flat (Vamana) variants ---
  - base_args: ['@metric']
    constructor: CPHNSW
    disabled: false
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw
    run_groups:
      M-32-1bit:
        args: [[32], [200], [1]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]
      M-32-2bit:
        args: [[32], [200], [2]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]
      M-32-4bit:
        args: [[32], [200], [4]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]

  # --- CP-HNSW HNSW (multi-layer) variants ---
  - base_args: ['@metric']
    constructor: CPHNSWHnsw
    disabled: false
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw-hnsw
    run_groups:
      M-32-1bit:
        args: [[32], [200], [1]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]
      M-32-2bit:
        args: [[32], [200], [2]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]
      M-32-4bit:
        args: [[32], [200], [4]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]

  # --- CP-HNSW GPU batch variant ---
  - base_args: ['@metric']
    constructor: CPHNSWGpu
    disabled: false
    gpu: true
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw-gpu
    run_groups:
      M-32-1bit:
        args: [[32], [200], [1]]
        query_args: [[10, 20, 40, 80, 100, 200, 400, 600, 800]]
