float:
  any:
  - base_args: ['@metric']
    constructor: CPHNSW
    disabled: false
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw
    run_groups:
      bits-1:
        args: [[1]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]
      bits-2:
        args: [[2]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]
      bits-4:
        args: [[4]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]

  - base_args: ['@metric']
    constructor: CPHNSWHnsw
    disabled: false
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw-hnsw
    run_groups:
      bits-1:
        args: [[1]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]
      bits-2:
        args: [[2]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]
      bits-4:
        args: [[4]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]

  - base_args: ['@metric']
    constructor: CPHNSWGpu
    disabled: false
    gpu: true
    singularity_image: cphnsw
    module: vibe.algorithms.cphnsw
    name: cphnsw-gpu
    run_groups:
      bits-1:
        args: [[1]]
        query_args: [[0.80, 0.90, 0.95, 0.97, 0.99]]
